image: node:14
stages:
  - install_dependencies
  - deploy

before_script:
  - apt-get update
  - apt-get install -y build-essential
  - yarn -D

install_dependencies:
  stage: install_dependencies
  script:
    - yarn config set prefix /usr/local
    - yarn global add serverless
    - yarn
    - export PROJECT_NAME
    - export AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY
    - sls config credentials -p aws -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY

start:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: develop
  script:
    - sls deploy
  except:
    - master


deploy:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: master
  script:
    - sls deploy
  only:
    - master
