image: registry.gitlab.com/dev_squad/ci-base-image:latest
stages:
  - install_dependencies
  - deploy

after_script:
  - echo ${CI_JOB_STAGE}:${CI_JOB_NAME} > LAST_JOB
  
install_dependencies:
  stage: install_dependencies
  script:
    - yarn
    - export PROJECT_NAME
    - export AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules

start:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: develop
  script:
    - yarn deploy:aws-config
    - yarn deploy:run
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  artifacts:
    when: always
    paths:
      - LAST_JOB
      - .serverless
  except:
    - master

deploy:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: master
  script:
    - ls -la 
    - yarn deploy:aws-config
    - yarn deploy:run
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  artifacts:
    when: always
    paths:
      - LAST_JOB
      - .serverless
  only:
    - master
