image: registry.gitlab.com/dev_squad/ci-base-image:latest
stages:
  - install_dependencies
  - test
  - deploy

after_script:
  - echo ${CI_JOB_STAGE}:${CI_JOB_NAME} > LAST_JOB
  
install_dependencies:
  stage: install_dependencies
  script:
    - yarn
    - export PROJECT_NAME
    - export AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules
  rules:
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

unit:
  stage: test
  script:
    - yarn test:ci
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  rules:
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

start:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: develop
  script:
    - ls -la
    - yarn lint .
    - yarn deploy:aws-config
    - yarn deploy:run
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  only:
    - master

deploy:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: master
  script:
    - ls -la 
    - yarn deploy:aws-config
    - yarn deploy:run
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  only:
    - master
