image: registry.gitlab.com/dev_squad/ci-base-image:latest
stages:
  - install_dependencies
  - test
  - deploy
after_script:
  - echo ${CI_JOB_STAGE}:${CI_JOB_NAME} > LAST_JOB
  
install_dependencies:
  stage: install_dependencies
  script:
    - npm i
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules
  rules:
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

unit:
  stage: test
  script:
    - npm run test:ci
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  rules:
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy:dev:
  stage: deploy
  script:
    - npm run deploy -- --stage=$CI_COMMIT_REF_SLUG
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  except:
    - master

deploy:live:
  stage: deploy
  variables:
    STAGE: live
    ENVIRONMENT_NAME: live
  script:
      - npm run deploy -- --stage=$CI_COMMIT_REF_SLUG
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  only:
    - master
