image: node:14
stages:
  - install_dependencies
  - deploy

after_script:
  - echo ${CI_JOB_STAGE}:${CI_JOB_NAME} > LAST_JOB

build_essential:
  stage: install_dependencies
  script:
  - apt-get update
  - apt-get install -y build-essential
  - yarn -D

install_dependencies:
  stage: install_dependencies
  script:
    - yarn config set prefix /usr/local
    - yarn global add serverless
    - yarn
    - export PROJECT_NAME
    - export AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY
    - sls config credentials -p aws -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules

start:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: develop
  script:
    - yarn deploy
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  except:
    - master

deploy:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: master
  script:
    - yarn deploy
  cache:
    key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - node_modules
  only:
    - master
