# Happy Coding!
service: webhooks

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:ENVIRONMENT_NAME}
  region: us-east-1
  environment:
    PROJECT_NAME: ${env:PROJECT_NAME}
    ENVIRONMENT_NAME: ${self:provider.stage}

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  healthCheck:
    handler: src/handlers/index.healthCheck
    events:
      - http:
          path: health-check
          method: get
